### ISSUE TITLE
traditional character Chinese translation ready to be added

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Cyclone-Center#88]
The traditional character Chinese translation is ready for deployment. It will need  #87 fixed, but everything on the translators side is done. The formatting with the characters  has also been checked and it looks okay. 

One other issue is that there is a message that pops up with 'Welcome, new stormwatcher! You can help us best by observing at least 4 storms. It’s quick, easy, and fun. When you’re ready, you can get started below!'  - @chrissnyder is that an intervention? the text isn't in the translation tool. If it is a intervention it will be shut off in the translated versions or do you need that text translation?

**Comment by mschwamb** [comment]
In case you need a translation for that 'Welcome, new stormwatcher..." part, I've got it for you:

Welcome, new stormwatcher! You can help us best by observing at least 4 storms. It’s quick, easy, and fun. When you’re ready, you can get started below!

歡迎，新來的追風者！你對我們最大的幫助是分析至少4個風暴，過程簡單迅速，而且很有趣。等你準備好就可以開始了！

**Comment by srallen** [comment]
@mschwamb, I'm working on getting these translations ready. I added the translation for the "Welcome, new stormwatcher!" text. 

There are a few other strings that need translation now. I resolved an issue I was having with deploying and discovered that a few strings for the slide-tutorial probably never made it up into the Zooniverse Translations app. This is fixed now and those strings are now needing translations in the interface. Could you take a look at it?

**Comment by mschwamb** [comment]
@srallen Thanks. I can't translate beyond more  than a few words myself, so I've passed it back to the translators. I'll let you know when they finish the new phrases.

**Comment by mschwamb** [comment]
@srallen everything should be translated now

**Comment by srallen** [comment]
@mschwamb, Great.  I've deployed it to the site. I've already seen a couple of issues that need to be addressed:
- The slide tutorial still is having translation issues. Even though translations are present now, it's still displaying in English.
- The drop down menu for the language selection should have a better label than the file name.

Could you look it over and add any issues if you see them?

**Comment by mschwamb** [comment]
@srallen You're checking the deploy from the translation tool website? I noticed it always say the temp json file name when you hit the deploy button and look at the preview. I'm not sure what's different when it's deployed on the production site, but any translation I've seen live doesn't have that issues even though it has the temp json name showing when you check it out the translation tool. So I think that @chrissnyder should know how that works. 

I find that both tutorials are stilling show up in English. 

![screen shot 2015-09-23 at 6 12 07 am](https://cloud.githubusercontent.com/assets/753325/10034479/93336342-61c3-11e5-8363-fff1abec6f74.png)

![screen shot 2015-09-23 at 6 12 11 am](https://cloud.githubusercontent.com/assets/753325/10034480/9336424c-61c3-11e5-8acc-b2cbd58f877b.png)

**Comment by srallen** [comment]
@mschwamb, thanks I'll work on fixing the slide tutorial today. I thought it was fixed and was displaying English because the translation for those strings weren't available yet (missing translations should fall back to English), but it's still broken somehow.

And thanks for the info about the preview, I didn't realize that showing the file name was expected for the preview. This is the first project I've worked on translation!

**Comment by srallen** [comment]
@mschwamb, the button ("Next" and "Finish") on the slide tutorial is now translating correctly, but the rest of the slide is not. I checked the translations tool website and the translations for the slides are missing for some reason. I'm not sure what happened and I apologize for the inconvenience. There was a DB outage this morning while I was working on this, so that might be related.

Aside from that I went ahead and deployed to production, so traditional Chinese is now available in the drop down on the actual site. The only thing missing are those slide translations.

**Comment by mschwamb** [comment]
I can ask the translator to do it again, but any way it's in a backup copy that's easy to get access to? 

@srallen  It's a little worrying that only those few bits of text aren't there when there was alot more on the slides to do. So I'm worried other text is messed up in the json and that's why those values aren't populated.

**Comment by mschwamb** [comment]
@srallen if you're confident that the translation json file is fine then I'll email the translator tomorrow morning (my time/ evening in Chicago today)

**Comment by srallen** [comment]
@mschwamb, I don't have a reason to think it's the json file that has issues, however, it is odd that the slide tutorial is now missing the translations that were present yesterday. I'm thinking either something happened when I deployed or something happened on the database side this morning while we were experiencing issues. 

@parrish, would there be any reason doing a seed-translation deploy overwrite existing saved translations? I ran the deploy script which includes seed-translations this morning. Are there any backups that can be retrieved? The Traditional Chinese translations were 100% complete yesterday and are now missing the translations for the slide tutorial.

**Comment by mschwamb** [comment]
@srallen  since you're confident nothing's wrong with the json I'll ask the translator to go back to those strings.

**Comment by mschwamb** [comment]
@srallen  you should be all set - the text for the slide tutorial should be complete again

**Comment by srallen** [comment]
@mschwamb, thanks for asking the translator to redo those slide translations. They are appearing correctly now, so I'll close the ticket. Do reopen if anything else comes up.

**Comment by mschwamb** [comment]
@srallen is this version live? I'm still seeing the english tutorial and slide tutorial. I just  checked in browser I've never gone to the site in (Safari) and I'm seeing English on those two sections.

**Comment by srallen** [comment]
It is in production, but I found its rendering has been inconsistent and I happened to see it rendered correctly earlier today. It seems to render in Chinese _most_ of the time, but not everytime. I still need to figure out why.

**Comment by srallen** [comment]
This issue was order of loading. I believe I now have the translations loading in the correct order so that it is appearing correctly.

**Comment by mschwamb** [comment]
I see the slide tutorial coming up in characters now, but not the other tutorial

![screen shot 2015-09-26 at 7 21 01 am](https://cloud.githubusercontent.com/assets/753325/10114154/4f6289f0-641f-11e5-9032-dad15f508f3d.png)

**Comment by srallen** [comment]
Content of the inline tutorial is now translating correctly except for the "Continue" button.

**Comment by mschwamb** [comment]
closing this - as this has been sorted
