### ISSUE TITLE
Replacing image in slide tutorial that's in English for traditional character Chinese version

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Cyclone-Center#97]
An animated image in the slide tutorial uses English words and that won't be helpful for non-English speakers to know what to do. @srallen and @chrissnyder can that be replaced with so in the traditional chinese version it shows up in traditional chinese characters?

![screen shot 2015-09-26 at 7 19 59 am](https://cloud.githubusercontent.com/assets/753325/10114179/969ca59e-641f-11e5-967a-3c801388269a.png)

**Comment by srallen** [comment]
There are two options for approaching this: we could add the image file to the translations interface and have different images available for different locales or it could be redesigned to remove the words entirely. I'm pinging our new designer @jwbmartin for input.

**Comment by mschwamb** [comment]
Before redesigning I think you should make sure the Cyclone Center research team are happy with that solution. It doesn't seem like it's a hugely important image that changing it to something else won't impact but user behavior, but when on  my main Zooniverse projects if something gets changed in the tutorial or interface I have to note in the paper and prove that it didn't change my results. (cc @chrissnyder)

**Comment by srallen** [comment]
Good point, also, there are many images in the field guide that have English in them, see #91.

**Comment by mschwamb** [comment]
I only saw the one, didn't realize the guide changes per task in the decision tree. I'll get the translator to work on those text

**Comment by mschwamb** [comment]
@srallen here's the translated text for the figures

Cold Band 冷雲帶
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/center-curved-band.jpg) 


Warm Wedge 尖角型暖區
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/center-curved-band.jpg)

Gray Swirl 灰色渦旋
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/center-shear.jpg)

Colors close together 顏色漸層密集
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/center-shear.jpg)

No circular cold cloud near center  中心附近沒有圓盤狀冷雲
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/curved-band.jpg)

Edge of satellite's view 衛星視角邊緣
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/edge.jpg)

Circular cold clouds 圓盤狀冷雲
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/embedded-center.jpg)

Light Blue is thick enough here...  此處淺藍色夠寬
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/exceeding.jpg)

... but not here 但是這裡不夠
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/exceeding.jpg)

Yellow is thick enough because it is layered under the blue  黃色夠寬，因為它位在藍色之下
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/exceeding.jpg)

Eye 風眼
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/eye.jpg)

Eyewall 眼牆
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/eye.jpg)

Cold Band doesn't go far around 冷雲帶並沒有延伸太遠
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/feature-embedded-center.jpg)

Warm Wedge is too short 尖角型暖區太短
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/feature-embedded-center.jpg)

Cold Band 冷雲帶
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/feature-eye.jpg)

Warm Band (Warm Wedge?) 尖角型暖區
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/feature-eye.jpg)

Future tropical cyclone? 未來的熱帶氣旋？
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/no-storm.jpg)

Cold Front 冷鋒
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/post-tropical.jpg)

Warm Front 暖鋒
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/post-tropical.jpg)

Gray Swirl 灰色渦旋
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/shear.jpg)

Colors close together 顏色漸層密集
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/shear.jpg)

Weakest 最弱
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/strength-chart.jpg)

Strongest 最強
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/strength-chart.jpg)

Stronger 較強
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/strength-chart.jpg)

Cyan broke here 此處藍綠色不連續
(https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/surrounding.jpg)

**Comment by srallen** [comment]
@mschwamb, could you have the translator look over the files changed in #98 to make sure the translations are correct in the field guide images? They should be able to see a preview of the images there before I merge them in and deploy them. I want to make sure I didn't make a mistake. Thanks!

**Comment by mschwamb** [comment]
Cool thanks @srallen . In the meantime what's left is that image from then tutorial that's got english text. Can you sort that in the meantime whether the new visual designer will come up with something else that the cyclone center team approves or that you'll make a traditional character chinese version and require some text?

**Comment by mschwamb** [comment]
Oh and email is in the translator to check over the images. I'll let you know when I hear back from her.

**Comment by mschwamb** [comment]
The font in the image linked below needs some changes. Otherwise the rest are fine.

@srallen from the translator:

 One of the characters looks different.And I would like to change the translation of the last sentence (see below). Although the new translation is not exactly the same as the orgional English, it reads better in Chinese.

Yellow is thick enough because it is layered under the blue 黃色夠寬，因為它位在藍色之下 (https://static.zooniverse.org/www.cyclonecenter.org/images/field-guide/exceeding.jpg)

Change it to 位在藍色之下的黃色夠寬

**Comment by srallen** [comment]
@mschwamb, I can get that updated today. Thank you for having them review.

I also talked to @jwbmartin about translating the gif and she has access to the original file and can get that done today. I sent her the strings for everything that shows up in the gif, but we don't have strings for "this" and "that" (the button placeholder text). Could you ask the translator to send us the translations for those? I know those words show up elsewhere, but I don't want to guess and get it wrong. Thanks!

**Comment by mschwamb** [comment]
@jwbmartin and @srallen  here's all the text on that image translated

This  這張
or  或
That  那張
Site Intro  網站介紹
Tutorial   導覽
Restart  重新開始
Guide  說明

**Comment by srallen** [comment]
@mschwamb, thank you! I've updated my pull request with the gifs and changes: https://github.com/zooniverse/Cyclone-Center/pull/98/files

Could the translator have one last look over? If it all looks ok, then I'll merge it in and deploy.

**Comment by mschwamb** [comment]
@srallen looks good. can you push it live

**Comment by srallen** [comment]
Just a small update: the field guide images translations are deployed and correctly displaying. There appears to be an issue with the slide tutorial getting the translated gifs. Probably similar issue as before, so hopefully I should have a fix shortly.

**Comment by mschwamb** [comment]
Thanks for the update @srallen. Any chance you can get to this before the end of the year? Thanks

**Comment by srallen** [comment]
Yeah I think I should be able to get to this before end of the year. Not sure exactly when though.
